### ISSUE TITLE
BLEU Score를 어떤 데이터셋으로 평가한것인지 궁금합니다.

### ISSUE THREAD

**Issue by gaeun0112** [KoJLabs/KoTAN#6]
huggingface model details에 작성된 bleu score가 어떤 test dataset을 통하여 얻은 결과인지 궁금합니다.

또한, 혹시 AI Hub에서 어떤 데이터를 활용하여 fine tuning 되었는지도 알 수 있을까요?

**Comment by juhwanlee-diquest** [comment]
안녕하세요, 답변이 늦어 죄송합니다.

저희는 학습을 위해 아래의 그림에 나온 데이터을 사용했습니다.


<img width="365" alt="스크린샷 2024-02-10 오전 10 35 02" src="https://github.com/trailerAI/KoTAN/assets/88358300/9e22b057-6668-4756-9230-756480f2faa3">
